create table if not exists polls (
  id text primary key,
  title text not null,
  category text not null,
  description text not null,
  featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists poll_options (
  id text primary key,
  poll_id text not null references polls(id) on delete cascade,
  label text not null,
  votes_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists votes (
  id bigint generated by default as identity primary key,
  poll_id text not null references polls(id) on delete cascade,
  option_id text not null references poll_options(id) on delete cascade,
  identity_key text not null,
  created_at timestamptz not null default now(),
  constraint votes_unique_identity_per_poll unique (poll_id, identity_key)
);

create index if not exists votes_poll_id_idx on votes (poll_id);
create index if not exists poll_options_poll_id_idx on poll_options (poll_id);

create or replace function increment_poll_option_votes()
returns trigger
language plpgsql
as $$
begin
  update poll_options
  set votes_count = votes_count + 1
  where id = new.option_id;

  return new;
end;
$$;

drop trigger if exists votes_after_insert on votes;
create trigger votes_after_insert
after insert on votes
for each row execute procedure increment_poll_option_votes();
