delete from votes;
delete from poll_options;
delete from polls;

insert into polls (id, title, category, description, featured) values
  ('one-piece-favorites', 'One Piece Favorites', 'Anime', 'Pick your favorite character from One Piece.', true),
  ('naruto-favorites', 'Naruto Favorites', 'Anime', 'Choose your favorite Naruto character.', false),
  ('bleach-favorites', 'Bleach Favorites', 'Anime', 'Pick your favorite Bleach character.', false),
  ('jjk-favorites', 'Jujutsu Kaisen Favorites', 'Anime', 'Choose your favorite JJK character.', false),
  ('chainsaw-man-favorites', 'Chainsaw Man Favorites', 'Anime', 'Pick your favorite Chainsaw Man character.', false),
  ('dragon-ball-favorites', 'Dragon Ball Favorites', 'Anime', 'Choose your favorite Dragon Ball character.', false),
  ('solo-leveling-favorites', 'Solo Leveling Favorites', 'Anime', 'Pick your favorite Solo Leveling character.', false),
  ('attack-on-titan-favorites', 'Attack on Titan Favorites', 'Anime', 'Choose your favorite AOT character.', false),
  ('demon-slayer-favorites', 'Demon Slayer Favorites', 'Anime', 'Pick your favorite Demon Slayer character.', false)
on conflict (id) do nothing;

insert into poll_options (id, poll_id, label, votes_count) values
  ('opc-1', 'one-piece-favorites', 'Monkey D. Luffy', 0),
  ('opc-2', 'one-piece-favorites', 'Roronoa Zoro', 0),
  ('opc-3', 'one-piece-favorites', 'Sanji', 0),
  ('opc-4', 'one-piece-favorites', 'Trafalgar D. Water Law', 0),
  ('opc-5', 'one-piece-favorites', 'Portgas D. Ace', 0),
  ('opc-6', 'one-piece-favorites', '"Red-Haired" Shanks', 0),
  ('opc-7', 'one-piece-favorites', 'Rocks D. Xebec', 0),
  ('nrc-1', 'naruto-favorites', 'Naruto Uzumaki', 0),
  ('nrc-2', 'naruto-favorites', 'Sasuke Uchiha', 0),
  ('nrc-3', 'naruto-favorites', 'Kakashi Hatake', 0),
  ('nrc-4', 'naruto-favorites', 'Itachi Uchiha', 0),
  ('nrc-5', 'naruto-favorites', 'Tobirama Senju', 0),
  ('blc-1', 'bleach-favorites', 'Ichigo Kurosaki', 0),
  ('blc-2', 'bleach-favorites', 'Rukia Kuchiki', 0),
  ('blc-3', 'bleach-favorites', 'Kisuke Urahara', 0),
  ('blc-4', 'bleach-favorites', 'Sosuke Aizen', 0),
  ('blc-5', 'bleach-favorites', 'Kenpachi Zaraki', 0),
  ('jjk-1', 'jjk-favorites', 'Satoru Gojo', 0),
  ('jjk-2', 'jjk-favorites', 'Yuji Itadori', 0),
  ('jjk-3', 'jjk-favorites', 'Ryomen Sukuna', 0),
  ('jjk-4', 'jjk-favorites', 'Yuta Okkotsu', 0),
  ('jjk-5', 'jjk-favorites', 'Kento Nanami', 0),
  ('jjk-6', 'jjk-favorites', 'Fushiguro Toji', 0),
  ('csm-1', 'chainsaw-man-favorites', 'Power', 0),
  ('csm-2', 'chainsaw-man-favorites', 'Denji', 0),
  ('csm-3', 'chainsaw-man-favorites', 'Makima', 0),
  ('csm-4', 'chainsaw-man-favorites', 'Aki Hayakawa', 0),
  ('csm-5', 'chainsaw-man-favorites', 'Reze', 0),
  ('dbz-1', 'dragon-ball-favorites', 'Goku', 0),
  ('dbz-2', 'dragon-ball-favorites', 'Vegeta', 0),
  ('dbz-3', 'dragon-ball-favorites', 'Gohan', 0),
  ('dbz-4', 'dragon-ball-favorites', 'Future Trunks', 0),
  ('dbz-5', 'dragon-ball-favorites', 'Piccolo', 0),
  ('sll-1', 'solo-leveling-favorites', 'Sung Jin-Woo', 0),
  ('sll-2', 'solo-leveling-favorites', 'Cha Hae-In', 0),
  ('sll-3', 'solo-leveling-favorites', 'Beru', 0),
  ('sll-4', 'solo-leveling-favorites', 'Igris', 0),
  ('sll-5', 'solo-leveling-favorites', 'Ashborn', 0),
  ('aot-1', 'attack-on-titan-favorites', 'Levi Ackerman', 0),
  ('aot-2', 'attack-on-titan-favorites', 'Eren Yeager', 0),
  ('aot-3', 'attack-on-titan-favorites', 'Mikasa Ackerman', 0),
  ('aot-4', 'attack-on-titan-favorites', 'Armin Arlert', 0),
  ('aot-5', 'attack-on-titan-favorites', 'Erwin Smith', 0),
  ('dms-1', 'demon-slayer-favorites', 'Tanjiro Kamado', 0),
  ('dms-2', 'demon-slayer-favorites', 'Inosuke Hashibira', 0),
  ('dms-3', 'demon-slayer-favorites', 'Giyu Tomioka', 0),
  ('dms-4', 'demon-slayer-favorites', 'Kyojuro Rengoku', 0),
  ('dms-5', 'demon-slayer-favorites', 'Shinobu Kocho', 0),
  ('dms-6', 'demon-slayer-favorites', 'Zenitsu Agatsuma', 0)
on conflict (id) do nothing;
